version: '3.8'

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SCHEDULER_INTERVAL=10s
    # depends_on:
      # - postgres
    restart: unless-stopped

#   postgres:
#     image: postgres:16-alpine
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=scheduler
#       - POSTGRES_PASSWORD=scheduler
#       - POSTGRES_DB=scheduler
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres_data:

